[package]
name = "cwe_checker"
version = "0.5.0"
authors = ["Enkelmann <nils-edvin.enkelmann@fkie.fraunhofer.de>"]
edition = "2018"

[dependencies]
structopt = "0.3"
cwe_checker_lib = { path = "../cwe_checker_lib" }
serde_json = "1.0"
directories = "3.0"
nix = "0.19.1"